-- Phase 3 (incremental): expand GameStat to store richer boxscore fields + performance rating
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "minutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "teamId" INTEGER;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "twoPtMade" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "twoPtAtt" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "threePtMade" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "threePtAtt" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "ftMade" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "ftAtt" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "dunks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "oreb" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "dreb" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "steals" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "blocks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "turnovers" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "fouls" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "plusMinus" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameStat" ADD COLUMN IF NOT EXISTS "performanceRating" DOUBLE PRECISION NOT NULL DEFAULT 0;
